name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'  # Esegui ogni giorno a mezzanotte UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: "False"  # Disabilita il "Code Time"
          SHOW_PROFILE_VIEWS: "False"  # Disabilita le visualizzazioni del profilo
          SHOW_LOC_CHART: "False"  # Disabilita la Timeline (chart delle linee di codice)
