name: Waka Readme

on:
  schedule:
    # Esegui ogni giorno a mezzanotte IST (ora indiana)
    - cron: '0 0 * * *'
  workflow_dispatch:  # Permette di eseguire l'azione manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
